language: ruby
services:
  - postgresql
before_script:
  - psql -c 'create database pgapp_test;' -U postgres
script:
 - gem install bundler
 - bundle install
 - bundle exec rake db:schema:load RAILS_ENV=test
 - bundle exec rake db:migrate
 - bundle exec rspec
